
export const REQUEST_LOADING_SIMILAR = 'REQUEST_LOADING_SIMILAR';
export const RECEIVE_SIMILAR = "RECEIVE_SIMILAR";
export const OFFER_MOVIE = "OFFER_MOVIE";

export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const RECEIVE_SEARCH_RESULT = 'RECEIVE_SEARCH_RESULT';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const CHOOSE_MOVIE = 'CHOOSE_MOVIE';